### ISSUE TITLE
Suggestion; multiple styles.

### ISSUE THREAD

**Issue by EthanHermsey** [khevamann/rn-responsive-styles#5]
In CSS libraries like tailwind and bootstrap you can give an element multiple classes, for example
 ```class="container center textBlue"```.

In rn-responsive-styles you can only get one style, so with multiple styles the style prop would look like 
```style={[ style('container'), style('center'), style('textBlue'), ]}```

I thought it would be nice to be able to do 
```style={ style('container center textBlue') }```

What do you think?

**Comment by khevamann** [comment]
I am a little hesitant on this just because I don't see a huge benefit. I don't think it is any more work to add styles in an array vs a list, and the default in react native is a list of styles like this library. Also, I think that would make the type checking impossible as I don't know how it could parse a list like this.

**Comment by EthanHermsey** [comment]
I see, those are good arguments. 
It would be a little less typing on the keyboard, but that does not weigh up to no type checking. 
It does fit better with the framework, keep it like it is :)
